name: Playwright Tests

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Setup Go for backend
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    # Setup Node.js for frontend
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    # Install backend dependencies and start server
    - name: Install Go dependencies
      working-directory: ./backend
      run: go mod tidy
    
    - name: Start backend server
      working-directory: ./backend
      run: |
        echo "Starting backend server..."
        echo "Current directory: $(pwd)"
        echo "Files in backend directory:"
        ls -la
        echo "Starting Go server..."
        go run . > backend.log 2>&1 &
        echo $! > backend.pid
        echo "Backend PID: $(cat backend.pid)"
        echo "Waiting for backend to start..."
        sleep 5
        echo "Initial backend log contents:"
        cat backend.log
        echo "Waiting additional 10 seconds..."
        sleep 10
        echo "Checking if backend is running..."
        if ! ps -p $(cat backend.pid) > /dev/null; then
          echo "Backend process died. Log contents:"
          cat backend.log
          exit 1
        fi
        echo "Backend process is still running. Log contents so far:"
        cat backend.log
        echo "Testing health endpoint..."
        for i in {1..15}; do
          if curl -f http://localhost:8080/health; then
            echo "Backend health check passed!"
            break
          else
            echo "Health check attempt $i failed, waiting 5 seconds..."
            sleep 5
          fi
        done
        # Test API endpoint
        echo "Testing API endpoint..."
        curl -f http://localhost:8080/api/seasons || (echo "API endpoint failed. Log contents:" && cat backend.log && exit 1)
    
    # Install e2e test dependencies
    - name: Install e2e test dependencies
      working-directory: ./e2e
      run: npm ci
    
    # Install Playwright browsers
    - name: Install Playwright Browsers
      working-directory: ./e2e
      run: npx playwright install --with-deps
    
    # Run Playwright tests
    - name: Run Playwright tests
      working-directory: ./e2e
      run: npx playwright test
      env:
        CI: true
    
    # Upload test results
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: |
          e2e/playwright-report/
          e2e/test-results/
        retention-days: 30