name: Playwright Tests

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Setup Go for backend
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    # Setup Node.js for frontend
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    # Install backend dependencies and start server
    - name: Install Go dependencies
      working-directory: ./backend
      run: go mod tidy
    
    - name: Start backend server
      working-directory: ./backend
      run: |
        echo "Starting backend server..."
        go run . > backend.log 2>&1 &
        echo $! > backend.pid
        echo "Backend PID: $(cat backend.pid)"
        sleep 10
        echo "Checking if backend is running..."
        if ! ps -p $(cat backend.pid) > /dev/null; then
          echo "Backend process died. Log contents:"
          cat backend.log
          exit 1
        fi
        echo "Testing API endpoint..."
        for i in {1..5}; do
          if curl -f http://localhost:8080/api/seasons; then
            echo "Backend is responding!"
            break
          else
            echo "Attempt $i failed, waiting 2 seconds..."
            sleep 2
          fi
        done
        # Final check
        curl -f http://localhost:8080/api/seasons || (echo "Backend failed to start after 5 attempts. Log contents:" && cat backend.log && exit 1)
    
    # Install frontend dependencies
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci
    
    # Install Playwright browsers
    - name: Install Playwright Browsers
      working-directory: ./frontend
      run: npx playwright install --with-deps
    
    # Run Playwright tests
    - name: Run Playwright tests
      working-directory: ./frontend
      run: npm run test
      env:
        CI: true
    
    # Upload test results
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: |
          frontend/playwright-report/
          frontend/test-results/
        retention-days: 30